<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ReplaceValuesSql</AssemblyName>
    <RootNamespace>ReplaceValuesSql</RootNamespace>
    <ApplicationIcon>Assets\replace-sql-values.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Tests\**" />
    <None Remove="Tests\**" />
    <EmbeddedResource Remove="Tests\**" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\replace-sql-values.ico" />
  </ItemGroup>
</Project>
